FROM mariadb:latest

# Copiar scripts SQL a la carpeta de inicialización
COPY init.sql /docker-entrypoint-initdb.d/

# Asegurar permisos correctos
RUN chmod 644 /docker-entrypoint-initdb.d/init.sql

# Variables de entorno por defecto (se pueden sobreescribir)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=loan_db
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin